In [15]:
import numpy as np
theta = np.array([-1, -1, -2, 0])
# assuming bias as 1 for the points. Does not matter since it will get multiplied by 0 of the theta vector. 
w1 = [[0 for i in range(4)] for j in range(4)]
w2 = [[0 for i in range(4)] for j in range(4)]
w1[0] = np.array([0,0,0,1])
w1[1] = np.array([1,0,0,1])
w1[2] = np.array([1,0,1,1])
w1[3] = np.array([1,1,0,1])
w2[0] = np.array([0,0,1,1])
w2[1] = np.array([0,1,1,1])
w2[2] = np.array([0,1,0,1])
w2[3] = np.array([1,1,1,1])

In [16]:
for j in range(0,7):
    print("For iteration no:", j, " ")
    for i in range(0,4):
        if (np.sign(np.dot(theta.transpose(), w1[i]))!= 1):
            theta = theta + w1[i]
            print(theta)
        if (np.sign(np.dot(theta.transpose(), w2[i]))!= -1):
            theta = theta - w2[i]
            print(theta)
    for i in range(0,4):
        print(np.sign(np.dot(theta.transpose(), w1[i])))
        print(np.sign(np.dot(theta.transpose(), w2[i])))

For iteration no: 0  
[-1 -1 -2  1]
[ 0 -1 -2  2]
[ 1 -1 -1  3]
[ 1 -2 -1  2]
[ 0 -3 -2  1]
1
-1
1
-1
-1
-1
-1
-1
For iteration no: 1  
[ 1 -3 -1  2]
[ 2 -2 -1  3]
[ 1 -3 -2  2]
1
0
1
-1
1
-1
0
-1
For iteration no: 2  
[ 1 -3 -3  1]
[ 2 -3 -2  2]
1
0
1
-1
1
-1
1
-1
For iteration no: 3  
[ 2 -3 -3  1]
[ 3 -3 -2  2]
[ 2 -4 -3  1]
1
-1
1
-1
0
-1
-1
-1
For iteration no: 4  
[ 3 -4 -2  2]
1
0
1
-1
1
-1
1
-1
For iteration no: 5  
[ 3 -4 -3  1]
[ 4 -3 -3  2]
[ 3 -4 -4  1]
1
-1
1
-1
0
-1
0
-1
For iteration no: 6  
[ 4 -4 -3  2]
1
-1
1
-1
1
-1
1
-1
